sudo: false
language: haskell
ghc:
- '7.8'
env:
  global:
    secure: "WCftMkV+uucDn280ZS/XusZISR+ZkBn0VWytk8EV5GnsndhA8UPGnwfxtm+wtmXrIqGXGLD04JY4irMOighEj2MjuON98W1jgtNh3TnxOakRZeIHMJlmr3V9NUuJdMnjUFmi6r2099fI4C7lgI26Mw1MuRnkK0UMh68HWz/mCCE="
deploy:
  provider: hackage
  username: StefanKersten
  password:
    secure: briz7H53NBiI44chLXZzyqI1mwrL9RPoo5aGE1IDS0MjvA52SMKMt4wmqGorFVJzV8LnePEaf+xYLCuXcsbMQxCSJR0/gXedOAtKe3YpFfce5Uy5YfPh86bzTQvs2Z3E8L3g0uBAtfalRJDpjxzwnfvWPHlcpGEQ8/VDwDxxdX8=
  on:
    repo: kaoskorobase/freesound
    branch: master
